version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'tweety'
      MYSQL_USER: 'mohan'
      MYSQL_PASSWORD: 'password10'
      MYSQL_ROOT_PASSWORD: 'password10'
    ports:
      - '3350:3306'
    expose:
      - '3350'
    volumes:
      - data_volume:/var/lib/mysql
volumes:
  data_volume: